// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from "react";
import ColorBadge from "./ColorBadge";
import { Flex } from "@chakra-ui/react";

// Arrays of color names and their codes
const colorNames = [
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Orange",
  "Purple",
  "Pink",
  "Brown",

  "White",
];

const colorCodes = [
  "#FF0E0E",
  "#0E4CFF",
  "#0EFF3E",
  "#FFF70E",
  "#ebff0e",
  "#A10EFF",
  "#FF0ED1",
  "#944a00",
  "#FFFFFF",
];

function getRandomIndexExcept(length: number, excludeIndex: number) {
  let idx;
  do {
    idx = Math.floor(Math.random() * length);
  } while (idx === excludeIndex);
  return idx;
}

const ColorBadgeList = () => {
  const badges = [];

  for (let i = 0; i < 50; i++) {
    // Randomly pick a color name and a color code, ensuring they don't match
    const nameIdx = Math.floor(Math.random() * colorNames.length);
    const colorIdx = getRandomIndexExcept(colorCodes.length, nameIdx);

    badges.push(
      <ColorBadge
        key={i}
        text={colorNames[nameIdx]}
        color={colorCodes[colorIdx]}
        top={""}
        left={""}
        bottom={""}
        right={""}
      />
    );
  }

  return (
    <Flex
      w={"full"}
      flexWrap={"wrap"}
      gap="5"
      p="4"
      justify={"center"}
      h={"fit-content"}
      align={"center"}
    >
      {badges}
    </Flex>
  );
};

export default ColorBadgeList;
